alias screen="grabvars;screen"
alias ch="pushd $HOME"
alias cd=pushd
alias d='dirs -v'
#alias +=pushd
#alias _=popd
alias cx='chmod +x'
alias grp='grep --exclude-dir=.svn --exclude=tags'
alias ntar="tar -cf"
alias gz="tar -zcvf"
alias bz="tar -jcvf"
alias zp="zip"
alias ugz="tar -zxf"
alias ubz="tar -jxf"
alias utar="tar -xf"
alias uzp="unzip"
alias ltar="tar -tf"
alias lbz="tar -jtf"
alias lgz="tar -ztf"
alias lzp="unzip -l"
alias llz="tar --lzma -tf"
alias ulz="tar --lzma -xf"
alias lz="tar --lzma -cvf"
alias g.="cd .."
alias g..="cd ../.."
alias g...="cd ../../.."
alias pr="ps -A | grep $1"
alias cfg="mvn compile exec:java"
alias start="apachectl start"
alias history="history | tee /Users/chetnachaudhari/history/history-`date '+%d-%m-%Y-%H:%M:%S'`.txt"
alias mci="mvn clean install"
alias cfg="mvn compile exec:java"
alias inodes_count="find .  -type f | cut -d "/" -f 2 | sort | uniq -c | sort -n"
alias inodes="find . -print | wc -l"
alias time2date='perl -e '\''print scalar(localtime shift), "\n"'\'''
alias jvmBasics="java -XX:+PrintFlagsFinal -version | grep -iE 'heapsize|permsize|threadstacksize'"
alias bytes2hr="awk '{ split( \"KB MB GB TB PB\" , v ); s=1; while( $1>1024 ){ $1/=1024; s++ } print int($1) v[s] }'"
alias sandbox="ssh root@localhost -p 2222"
alias ms="mvn sonar:sonar"
alias cdfcli="cd ~/git/fulcrum/fulcrum-cli"
alias compile_hive="mvn clean install -Phadoop-2,dist -DskipTests"
alias getMyIp="ipconfig getifaddr en0"
alias ll="ls -lGh"
## Show hidden files ##
alias l.='ls -d .* --color=auto'
alias diff='vimdiff'
alias nowdate='date +"%d-%m-%Y"'
alias df='df -H'
alias du='du -ch'
alias fhere="find . -name "
